CRUDCaminhoes/CRUDCaminhoes/Models/CaminhaoModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CRUDCaminhoes.Models
{
    public class CaminhaoModel
    {
        public int Id { get; set; }
       
        public string Nome { set; get; }
        public string Descricao { get; set; }
        public DateTime DataDeCriacao { get; set; }

    }
}

CRUDCaminhoes/CRUDCaminhoes/Models/ErrorViewModel.cs
using System;

namespace CRUDCaminhoes.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CRUDCaminhoes/CRUDCaminhoes/Controllers/CaminhaoController.cs
using CRUDCaminhoes.Models;
using CRUDCaminhoes.Repositorio;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CRUDCaminhoes.Controllers
{
    public class CaminhaoController : Controller
    {

        private readonly ICaminhaoRepositorio _caminhaoRepositorio;       

        public CaminhaoController(ICaminhaoRepositorio caminhaoRepositorio)
        {
            _caminhaoRepositorio = caminhaoRepositorio;
        }

        public IActionResult Index()
        {
            List<CaminhaoModel> caminhoes = _caminhaoRepositorio.BuscarTodos();
            return View(caminhoes);
        }

        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(CaminhaoModel caminhao)
        {
            if (ModelState.IsValid)
            {
                _caminhaoRepositorio.Adicionar(caminhao);
                return RedirectToAction("Index");
            }
            return View(caminhao);
        }

        public IActionResult Editar(int id)
        {
            if (ModelState.IsValid)
            {
                CaminhaoModel caminhao = _caminhaoRepositorio.ListarPorId(id);
                return View(caminhao);
            }

            return View("Editar", id);
        }

        [HttpPost]
        public IActionResult Alterar(CaminhaoModel caminhao)
        {
            _caminhaoRepositorio.Atualizar(caminhao);
            return RedirectToAction("Index");
        }

        public IActionResult Detalhes(int id)
        {
            CaminhaoModel caminhao = _caminhaoRepositorio.ListarPorId(id);
            return View(caminhao);
        }

        public IActionResult DeletarConfirmar(int id)
        {
            CaminhaoModel caminhao = _caminhaoRepositorio.ListarPorId(id);
            return View(caminhao);
        }

        public IActionResult Deletar(int id)
        {
            _caminhaoRepositorio.Apagar(id);
            return RedirectToAction("Index");

        }

    }
}

CRUDCaminhoes/CRUDCaminhoes/Controllers/HomeController.cs
using CRUDCaminhoes.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CRUDCaminhoes.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CRUDCaminhoes/CRUDCaminhoes/Views/Caminhao/Cadastrar.cshtml
@model CaminhaoModel

@{
    ViewData["Title"] = "Cadastro";
}

<div class="text-center">
    
    <h1 class="display-4" >Cadastrar Caminhão</h1>

</div>

<form asp-controller="Caminhao" asp-action="Cadastrar" method="post">
    <div class="form-group">
        <label for="Nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" aria-required="true">
    </div>

    <div class="form-group">
        <label for="Descricao">Descrição</label>
        <input type="text" asp-for="Descricao" class="form-control" aria-required="true">
    </div>

    <div class="form-group">
        <label for="DataDeCriacao">Data de Criação</label>
        <input type="date" asp-for="DataDeCriacao" class="form-control" aria-required="true">
    </div>

    <button type="submit" class="btn btn-primary" >Cadastrar</button>
    <a class="btn btn-secondary" asp-controller="Caminhao" asp-action="Index">Voltar</a>
</form>

CRUDCaminhoes/CRUDCaminhoes/Views/Caminhao/Deletar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

CRUDCaminhoes/CRUDCaminhoes/Views/Caminhao/DeletarConfirmar.cshtml
@model CaminhaoModel

@{
    ViewData["Title"] = "Listagem de Contatos";
}

<div class="text-center">
    <h3>Deseja apagar este registro?</h3>
</div>


<form asp-controller="Caminhao" asp-action="Alterar" method="post">
    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label for="Nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" readonly>
    </div>

    <div class="form-group">
        <label for="Descricao">Descrição</label>
        <input type="text" asp-for="Descricao" class="form-control" readonly>
    </div>

    <div class="form-group">
        <label for="DataDeCriacao">Data de Criação</label>
        <input type="datetime" asp-for="DataDeCriacao" class="form-control" readonly>
    </div>

    <a class="btn btn-outline-primary btn-block" role="button" asp-controller="Caminhao" asp-action="Index">Cancelar</a>
    <a class="btn btn-outline-danger btn-block" role="button" asp-controller="Caminhao" asp-action="Deletar" asp-route-id="@Model.Id">Confirmar</a>
</form>

CRUDCaminhoes/CRUDCaminhoes/Views/Caminhao/Detalhes.cshtml
@model CaminhaoModel

@{
    ViewData["Title"] = "Listagem de Contatos";
}

<div class="text-center">
    <h3>Detalhes do registro</h3>
</div>


<form>
    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label for="Nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" readonly>
    </div>

    <div class="form-group">
        <label for="Descricao">Descrição</label>
        <input type="text" asp-for="Descricao" class="form-control" readonly>
    </div>

    <div class="form-group">
        <label for="DataDeCriacao">Data de Criação</label>
        <input type="datetime" asp-for="DataDeCriacao" class="form-control" readonly>
    </div>

    <a class="btn btn-outline-primary btn-block" role="button" asp-controller="Caminhao" asp-action="Index">Voltar</a>

</form>

CRUDCaminhoes/CRUDCaminhoes/Views/Caminhao/Editar.cshtml
@model CaminhaoModel

@{
    ViewData["Title"] = "Editar";
}

<div class="text-center">

    <h1 class="display-4">Editar Caminhão</h1>

</div>

<form asp-controller="Caminhao" asp-action="Alterar" method="post">
   <input type="hidden" asp-for="Id" /> 

    <div class="form-group">
        <label for="Nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control">
    </div>

    <div class="form-group">
        <label for="Descricao">Descrição</label>
        <input type="text" asp-for="Descricao" class="form-control">
    </div>

    <div class="form-group">
        <label for="DataDeCriacao">Data de Criação</label>
        <input type="datetime" asp-for="DataDeCriacao" class="form-control">
    </div>

    <button type="submit" class="btn btn-primary">Alterar</button>
    <a class="btn btn-secondary" asp-controller="Caminhao" asp-action="Index">Voltar</a>
</form>

CRUDCaminhoes/CRUDCaminhoes/Views/Caminhao/Index.cshtml
@model List<CaminhaoModel> 
@{
    ViewData["Title"] = "Listagem de Contatos";
}

<div class="d-grid gap-2 d-md-flex justify-content-md-start">
    <a class="btn btn-success" role="button" asp-controller="Caminhao" asp-action="Cadastrar">Cadastrar</a>
</div>


<h1>Listagem  </h1>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Nome</th>
            <th scope="col">Descrição</th>
            <th scope="col">Data de Criação</th>
            <th scope="col"></th>
        </tr>
    </thead>

    <tbody>
        @if(Model != null && Model.Any())
         {
                foreach (CaminhaoModel caminhao in Model)
                {
                          <tr>
                                <th>@caminhao.Nome</th>
                                <th>@caminhao.Descricao</th>
                                <th>@caminhao.DataDeCriacao</th>
                                <td>
                                    <div class="btn-group" role="group">
                                        <a role="button" class="btn btn-outline-primary" asp-route-id="@caminhao.Id" asp-controller="Caminhao" asp-action="Editar">Editar</a>
                                        <a role="button" class="btn btn-outline-info" asp-route-id="@caminhao.Id" asp-controller="Caminhao" asp-action="Detalhes">Detalhes</a>
                                        <a role="button" class="btn btn-outline-danger" asp-route-id="@caminhao.Id" asp-controller="Caminhao" asp-action="DeletarConfirmar">Excluir</a>
                                    </div>
                                </td>
                           </tr>
                }
         }


    </tbody>
</table>

CRUDCaminhoes/CRUDCaminhoes/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Gerenciamento de Caminhões";
}

<div class="text-center">
    <h1 class="display-4">Semana 5-6</h1>
    <p>Aplicação Web com ASP.Net Core MVC.</p>
    <p>CRUD de caminhões.</p>
</div>

CRUDCaminhoes/CRUDCaminhoes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUDCaminhoes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CRUD Caminhões</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Caminhao" asp-action="Index">Caminhões</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Sistema de Gerenciamento de Caminhões
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>